name: RedEdit
main: com.boydti.rededit.RedEditBukkit
version: ${version}
description: RedEdit plugin
authors: [Empire92]
softdepend: [Vault, FastAsyncWorldEdit, WorldEdit]
load: STARTUP
database: false
permissions:
  rededit.tp.disabled:
    description: Tptoggle perm
    default: false